# Generated by Django 4.2.17 on 2025-01-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='lunch', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('italian', 'Italian'), ('mexican', 'Mexican'), ('indian', 'Indian'), ('chinese', 'Chinese'), ('american', 'American'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='diet',
            field=models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('gluten_free', 'Gluten-Free'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('none', 'None')], default='none', max_length=50),
        ),
    ]
